# Generated by Django 6.0.1 on 2026-01-14 10:52

from django.db import migrations

def backfill_names(apps, schema_editor):
    ExpenditureRequest = apps.get_model('financials', 'ExpenditureRequest')
    
    for req in ExpenditureRequest.objects.all():
        changed = False
        # Handle Requester
        if req.requester and not req.requester_name:
            # Note: We cannot use .get_full_name() on historical models in migrations
            # We must access fields directly.
            full_name = f"{req.requester.first_name} {req.requester.last_name}".strip()
            req.requester_name = full_name if full_name else req.requester.username
            changed = True
            
        # Handle Approver
        if req.approver and not req.approver_name:
            full_name = f"{req.approver.first_name} {req.approver.last_name}".strip()
            req.approver_name = full_name if full_name else req.approver.username
            changed = True
            
        if changed:
            req.save()

def reverse_backfill(apps, schema_editor):
    # We don't need to remove the names if we roll back, 
    # but strictly speaking, a reverse operation could clear them.
    # For now, we'll leave it as a no-op or clear them if strictness is required.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_expenditurerequest_approver_name_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_names, reverse_backfill),
    ]