# Generated by Django - Data migration to backfill payment_method_name

from django.db import migrations


def backfill_payment_method_names(apps, schema_editor):
    """
    Backfill payment_method_name for existing Payment and ExpenditureRequest records.
    This ensures historical records have the snapshot field populated.
    """
    Payment = apps.get_model('financials', 'Payment')
    ExpenditureRequest = apps.get_model('financials', 'ExpenditureRequest')
    
    # Backfill Payment records
    payments_updated = 0
    for payment in Payment.objects.filter(
        method__isnull=False,
        payment_method_name__isnull=True
    ).select_related('method'):
        payment.payment_method_name = payment.method.name
        payment.save(update_fields=['payment_method_name'])
        payments_updated += 1
    
    # Backfill ExpenditureRequest records
    expenditures_updated = 0
    for expenditure in ExpenditureRequest.objects.filter(
        payment_method__isnull=False,
        payment_method_name__isnull=True
    ).select_related('payment_method'):
        expenditure.payment_method_name = expenditure.payment_method.name
        expenditure.save(update_fields=['payment_method_name'])
        expenditures_updated += 1
    
    if payments_updated or expenditures_updated:
        print(f"\nBackfilled {payments_updated} payments and {expenditures_updated} expenditure requests with payment method names.")


def reverse_backfill(apps, schema_editor):
    """
    Reverse the backfill by setting payment_method_name to NULL.
    Only clears records that still have the FK relationship intact.
    """
    Payment = apps.get_model('financials', 'Payment')
    ExpenditureRequest = apps.get_model('financials', 'ExpenditureRequest')
    
    # Clear Payment records that still have method FK
    Payment.objects.filter(method__isnull=False).update(payment_method_name=None)
    
    # Clear ExpenditureRequest records that still have payment_method FK
    ExpenditureRequest.objects.filter(payment_method__isnull=False).update(payment_method_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_expenditurerequest_payment_method_name_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_method_names, reverse_backfill),
    ]
