# Generated by Django 6.0.1 on 2026-01-18 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_remove_task_next_payment_date_remove_task_paid_date'),
        ('financials', '0006_backfill_payment_method_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Expenditure', 'Expenditure'), ('Revenue', 'Revenue')], default='Expenditure', max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('cost_type', models.CharField(blank=True, choices=[('Additive', 'Additive'), ('Subtractive', 'Subtractive'), ('Inclusive', 'Inclusive')], max_length=20, null=True)),
                ('requester_name', models.CharField(blank=True, max_length=150, null=True)),
                ('approver_name', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_method_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.paymentcategory')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.paymentmethod')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_requests_made', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_requests', to='Eapp.task')),
            ],
            options={
                'verbose_name_plural': 'Transaction Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ExpenditureRequest',
        ),
    ]
