# Generated by Django 5.2.7 on 2026-01-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='next_payment_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='paid_date',
        ),
    ]
