# Generated by Django 6.0.1 on 2026-01-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0003_remove_task_next_payment_date_remove_task_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workshop_technician',
        ),
    ]
