# Generated by Django 6.0.1 on 2026-01-23 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_convert_location_to_fk'),
        ('common', '0004_add_location_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_location',
            field=models.ForeignKey(help_text='Current location of the task', on_delete=django.db.models.deletion.PROTECT, related_name='current_tasks', to='common.location'),
        ),
    ]
