# Generated by Django 6.0.1 on 2026-01-23 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0005_convert_current_location'),
        ('common', '0004_add_location_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='original_location_snapshot',
            field=models.ForeignKey(blank=True, help_text='Snapshot of original location before workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_tasks', to='common.location'),
        ),
    ]
