# Generated by Django 5.2.7 on 2025-11-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0007_alter_taskactivity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='approved_at',
            new_name='latest_pickup_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_out',
        ),
        migrations.RemoveField(
            model_name='task',
            name='original_location',
        ),
        migrations.RemoveField(
            model_name='task',
            name='original_technician',
        ),
        migrations.RemoveField(
            model_name='task',
            name='qc_rejected_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='qc_rejected_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sent_out_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workshop_returned_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workshop_sent_at',
        ),
        migrations.AddField(
            model_name='task',
            name='latest_pickup_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_pickup_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='original_location_snapshot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='original_technician_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_technician_snapshot_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='type',
            field=models.CharField(choices=[('status_update', 'Status Update'), ('note', 'Note'), ('diagnosis', 'Diagnosis'), ('customer_contact', 'Customer Contact'), ('intake', 'Intake'), ('workshop', 'Workshop'), ('rejected', 'Rejected'), ('ready', 'Ready'), ('returned', 'Returned'), ('picked_up', 'Picked Up'), ('device_note', 'Device Note'), ('assignment', 'Assignment')], max_length=20),
        ),
    ]
