# Generated by Django 6.0.1 on 2026-01-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0006_alter_task_original_location_snapshot'),
        ('Eapp', '0007_add_is_terminated'),
    ]

    operations = [
    ]
