# Generated by Django 6.0.1 on 2026-01-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0008_merge_20260124_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Parts', 'Awaiting Parts'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Picked Up', 'Picked Up')], db_index=True, default='Pending', max_length=20),
        ),
    ]
