# Generated by Django 6.0.1 on 2026-01-24 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0009_alter_task_status'),
        ('common', '0004_add_location_is_active'),
        ('customers', '0002_expand_phone_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when task was marked as Completed', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_technicians',
            field=models.JSONField(blank=True, default=list, help_text='List of {user_id, name, role, assigned_at} for all technicians involved'),
        ),
        migrations.AddField(
            model_name='task',
            name='first_assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of first technician assignment', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='return_count',
            field=models.IntegerField(default=0, help_text='Number of times task was returned to customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='return_periods',
            field=models.JSONField(blank=True, default=list, help_text='List of {returned_at, reassigned_at} ISO timestamp pairs for net execution calculation'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['first_assigned_at', 'completed_at'], name='idx_task_execution'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed_at', 'status'], name='idx_task_completed'),
        ),
    ]
