# Generated by Django 6.0.1 on 2026-01-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0010_add_execution_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
