# Generated by Django 6.0.1 on 2026-01-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0011_remove_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='qc_notes',
        ),
    ]
