# Generated by Django 6.0.1 on 2026-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0012_remove_task_qc_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workshop_periods',
            field=models.JSONField(blank=True, default=list, help_text='List of {sent_at, returned_at} ISO timestamp pairs excluding external workshop time'),
        ),
    ]
