# Generated by Django 6.0.1 on 2026-01-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0013_task_workshop_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ready_for_pickup_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when task was marked as Ready for Pickup', null=True),
        ),
    ]
