# Generated by Django 6.0.1 on 2026-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eapp', '0014_task_ready_for_pickup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='to_be_checked',
            field=models.BooleanField(default=False, help_text='Indicates task outcome requires verification by original technician'),
        ),
    ]
