# Generated by Django 5.2.7 on 2026-01-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_add_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_name',
            field=models.CharField(default='A PLUS EXPRESS TECHNOLOGIES LTD', help_text='Company name displayed in SMS messages', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_phone_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of company contact phone numbers'),
        ),
    ]
