# Generated by Django 5.2.7 on 2026-01-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_add_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_pickup_reminders_enabled',
            field=models.BooleanField(default=False, help_text='Automatically send SMS reminders for tasks ready for pickup'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='pickup_reminder_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours between pickup reminder messages'),
        ),
    ]
