# Generated by Django 6.0.1 on 2026-01-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systemsettings_auto_pickup_reminders_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_debt_reminders_enabled',
            field=models.BooleanField(default=False, help_text='Automatically send SMS reminders for tasks with outstanding debts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='debt_reminder_hours',
            field=models.PositiveIntegerField(default=72, help_text='Hours between debt reminder messages'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='debt_reminder_max_days',
            field=models.PositiveIntegerField(default=30, help_text='Stop sending reminders after this many days since pickup'),
        ),
    ]
