# Generated by Django 6.0.1 on 2026-03-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_add_debt_reminder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_sms_on_picked_up',
            field=models.BooleanField(default=True, help_text='Automatically send SMS when task is picked up (thank you / debt reminder)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_sms_on_ready_for_pickup',
            field=models.BooleanField(default=True, help_text='Automatically send SMS when task is approved/ready for pickup'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='pickup_deadline_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days customers have to pick up their devices'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='storage_fee_per_day',
            field=models.PositiveIntegerField(default=3000, help_text='Daily storage fee in TSH, used in SMS templates'),
        ),
    ]
