# Generated by Django 6.0.1 on 2026-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_encrypt_sensitive_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
