# Generated by Django 5.2.7 on 2025-12-23 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(help_text='Phone number the message was sent to', max_length=20)),
                ('message_content', models.TextField(help_text='Content of the SMS message')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data from Briq API', null=True)),
                ('sent_by', models.ForeignKey(help_text='User who sent the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The task this message is related to', on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='Eapp.task')),
            ],
            options={
                'verbose_name': 'Message Log',
                'verbose_name_plural': 'Message Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
