# Generated by Django 5.2.7 on 2026-01-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('received', 'Device Received'), ('progress', 'In Progress'), ('pickup', 'Ready for Pickup'), ('reminder', 'Pickup Reminder'), ('overdue', 'Overdue Notice'), ('quote', 'Quote Sent'), ('general', 'General Announcement')], default='general', max_length=20)),
                ('content', models.TextField(help_text='Message content. Variables: {customer}, {device}, {taskId}, {amount}, {daysWaiting}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['name'],
            },
        ),
    ]
