# Generated by Django 5.2.7 on 2026-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_wipe_all_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
