# Generated by Django 6.0.1 on 2026-01-14 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_remove_messagetemplate_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('pickup_reminder', 'Pickup Reminders'), ('debt_reminder', 'Debt Reminders')], max_length=50)),
                ('tasks_found', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_failed', models.PositiveIntegerField(default=0)),
                ('failure_details', models.JSONField(blank=True, default=list, help_text='List of {task_id, task_title, error} objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ManyToManyField(blank=True, help_text='Users who have seen this notification', related_name='acknowledged_scheduler_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheduler Notification',
                'verbose_name_plural': 'Scheduler Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
