"""
Django settings for A_express project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")

PROJECT_ROOT = (
    BASE_DIR.parent
)  # This goes up one level from A_express to django_backend
sys.path.insert(0, str(PROJECT_ROOT))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    # Allow a development-only fallback when DEBUG would be True
    if os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes"):
        SECRET_KEY = "dev-only-insecure-key-do-not-use-in-production"
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "The SECRET_KEY environment variable is required. "
            "Set it in your environment or .env file."
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# Production security settings for data in transit
if not DEBUG:
    # HTTP Strict Transport Security - force HTTPS for 1 year
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Railway uses a reverse proxy - trust X-Forwarded-Proto header
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # DON'T redirect HTTP→HTTPS - Railway's proxy handles this
    # Setting this to True causes redirect loops with Railway
    SECURE_SSL_REDIRECT = False
    
    # Secure cookies - only send over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Prevent browsers from guessing content types
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Railway provides RAILWAY_PUBLIC_DOMAIN
RAILWAY_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "healthcheck.railway.app",  # Railway healthcheck
    ".railway.app",  # All Railway subdomains
    ".railway.internal",  # Railway internal network (for Next.js proxy)
]
if RAILWAY_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_DOMAIN)

# CORS settings for allowing frontend to access backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Ensure FRONTEND_URL has a scheme (https://) before adding to CORS
if FRONTEND_URL:
    # Add https:// if missing
    if not FRONTEND_URL.startswith("http://") and not FRONTEND_URL.startswith("https://"):
        FRONTEND_URL = f"https://{FRONTEND_URL}"
    if FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.app\.github\.dev$",
    r"^https://.*\.gitpod\.io$",
    r"^https://.*\.railway\.app$",
    r"^https://.*\.vercel\.app$",
]

CSRF_TRUSTED_ORIGINS = [
    "https://localhost:8000",
    "https://127.0.0.1:8000",
    "https://*.app.github.dev",
    "https://*.railway.app",
]
if FRONTEND_URL.startswith("https://"):
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

# Allow cookies in CORS requests (required for HttpOnly cookie auth)
CORS_ALLOW_CREDENTIALS = True

# Cookie settings for JWT tokens
JWT_AUTH_COOKIE = 'access_token'
JWT_AUTH_REFRESH_COOKIE = 'refresh_token'
JWT_AUTH_COOKIE_SECURE = not DEBUG  # True in production (HTTPS only)
JWT_AUTH_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'  # None for cross-origin in production
JWT_AUTH_COOKIE_HTTPONLY = True  # Prevent JavaScript access
JWT_AUTH_COOKIE_PATH = '/'


# Application definition

# Check if Cloudinary is configured (before INSTALLED_APPS definition)
_CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL', '')
_USE_CLOUDINARY = bool(_CLOUDINARY_URL)

# DEBUG: Print to Railway logs on startup


INSTALLED_APPS = [
    "daphne",  # ASGI server for Django Channels (must be before django apps)
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # For media-only Cloudinary use, cloudinary_storage comes AFTER staticfiles
    *(['cloudinary_storage', 'cloudinary'] if _USE_CLOUDINARY else []),
    "channels",  # Django Channels for WebSocket support
    "corsheaders",
    "axes",  # Brute-force protection
    "users",
    "financials",
    "Eapp",
    "common",
    "customers",
    "rest_framework",
    "reports",
    "messaging",  # SMS messaging via Briq
    "settings",  # System settings
    "notifications",  # WebSocket notifications
    'django_extensions',
    'django_apscheduler',  # Background task scheduling
    # Debug tools - only enabled in development
    *(['debug_toolbar', 'silk'] if DEBUG else []),
]

MIDDLEWARE = [
    # Debug tools - only in development
    *(['debug_toolbar.middleware.DebugToolbarMiddleware'] if DEBUG else []),
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    *(['silk.middleware.SilkyMiddleware'] if DEBUG else []),  # Silk profiling (after auth)
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",  # Account lockout after failed attempts
]

ROOT_URLCONF = "A_express.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "A_express.wsgi.application"
ASGI_APPLICATION = "A_express.asgi.application"

# Channel Layers for WebSocket support
# InMemoryChannelLayer for single-instance deployment
# Switch to Redis if scaling to multiple instances
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    } if os.environ.get('REDIS_URL') else {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL from Railway if available
# Support for PgBouncer: If PGBOUNCER_URL is set, use it instead for better connection pooling
PGBOUNCER_URL = os.environ.get("PGBOUNCER_URL")
DATABASE_URL = os.environ.get("DATABASE_URL")

# Prefer PgBouncer for connection pooling if available
ACTIVE_DB_URL = PGBOUNCER_URL if PGBOUNCER_URL else DATABASE_URL

if ACTIVE_DB_URL:
    # Production: Use PostgreSQL (via PgBouncer if PGBOUNCER_URL is set)
    DATABASES = {
        "default": dj_database_url.config(
            default=ACTIVE_DB_URL,
            # Disable Django's connection pooling when using PgBouncer (conn_max_age=0)
            # Otherwise use 10-minute pooling for direct PostgreSQL connections
            conn_max_age=0 if PGBOUNCER_URL else 600,
            conn_health_checks=True,
        )
    }
else:
    # Local development: Try MySQL, fallback to SQLite
    try:
        import MySQLdb  # noqa: F401
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": "my_database_test",
                "USER": "root",
                "PASSWORD": "",
                "HOST": "127.0.0.1",
                "PORT": "3306",
            }
        }
    except ImportError:
        # SQLite fallback if MySQL not available
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


AUTH_USER_MODEL = "users.User"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CookieJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # Fallback for testing
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

# JWT Settings - Access token 15 min for security, silent refresh handles UX
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # Short for security
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# =============================================================================
# Media Storage Configuration
# =============================================================================
# Cloudinary: Free 25GB storage, auto-configured via CLOUDINARY_URL
# Local dev: filesystem storage when CLOUDINARY_URL not set

# Always define MEDIA_ROOT for safety (used by migrations, admin, etc.)
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

if _USE_CLOUDINARY:
    # Parse CLOUDINARY_URL: cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    import cloudinary
    
    cloudinary_url = _CLOUDINARY_URL
    _cloud_name = ''
    _api_key = ''
    _api_secret = ''
    
    if cloudinary_url.startswith('cloudinary://'):
        url_without_protocol = cloudinary_url[13:]
        if '@' in url_without_protocol:
            credentials, _cloud_name = url_without_protocol.rsplit('@', 1)
            if ':' in credentials:
                _api_key, _api_secret = credentials.split(':', 1)
    
    # Configure cloudinary library directly
    cloudinary.config(
        cloud_name=_cloud_name,
        api_key=_api_key,
        api_secret=_api_secret,
        secure=True
    )

    
    # CRITICAL: django-cloudinary-storage reads from this settings dict
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': _cloud_name,
        'API_KEY': _api_key,
        'API_SECRET': _api_secret,
    }
    
    # Django 5.1+ uses STORAGES dict instead of DEFAULT_FILE_STORAGE
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    MEDIA_URL = '/media/'
else:
    # Local development - use filesystem storage
    MEDIA_URL = "/api/media/"

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Dar_es_Salaam"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Django-Axes: Brute-force protection settings
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # Required for axes
    "django.contrib.auth.backends.ModelBackend",
]

# Axes configuration - account lockout after failed attempts
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 0.5  # Hours (30 minutes)
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]  # Lock by username+IP combo
AXES_RESET_ON_SUCCESS = True  # Reset counter on successful login
AXES_LOCKOUT_CALLABLE = None  # Use default lockout response
AXES_VERBOSE = False  # Don't log to console in production

# =============================================================================
# Briq SMS API Configuration
# =============================================================================
# Get your API key from: https://briq.tz/login
BRIQ_API_KEY = os.environ.get('BRIQ_API_KEY', '')
BRIQ_SENDER_ID = os.environ.get('BRIQ_SENDER_ID', 'A-EXPRESS')

# =============================================================================
# APScheduler Configuration
# =============================================================================
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# =============================================================================
# Django Debug Toolbar Configuration
# =============================================================================
INTERNAL_IPS = [
    '127.0.0.1',
]

